services:
    db:
        ports:
            - $LISTEN_DB:3306

    app:
        links:
            - mailpit
        volumes:
            - ./docker/app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro

    web:
        ports:
            - $LISTEN_WEB:80

    mailpit:
        image: axllent/mailpit
        ports:
            - $LISTEN_MAILPIT:8025