version: '2.4'
services:
    redis:
        image: redis:3

    db:
        image: mariadb:10
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            - "MYSQL_ROOT_PASSWORD"
            - "MYSQL_DATABASE=app"
        volumes:
            - /etc/localtime:/etc/localtime:ro

    app_base:
        build:
            context: ./docker/app
            args:
                - XDEBUG
                - CONTAINER_USER
                - PHP_VERSION
        working_dir: /var/www/app

    app:
        extends: app_base
        links:
            - redis
            - db
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./docker/app/app.ini:/usr/local/etc/php/conf.d/app.ini:ro
            - ./docker/app/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-php-fpm.conf:ro
            - ./:/var/www/app:rw

    web:
        image: nginx
        links:
            - app
        volumes:
          - ./docker/web/app.conf:/etc/nginx/conf.d/app.conf:ro
        volumes_from:
            - app